# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  frontend:
    name: Frontend (React) Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run ESLint (frontend)
        working-directory: ./frontend
        run: npx eslint . --ext .js,.jsx,.ts,.tsx > lint-frontend.txt || true

      - name: Upload ESLint Artifact (frontend)
        uses: actions/upload-artifact@v4
        with:
          name: lint-frontend.txt
          path: frontend/lint-frontend.txt

      - name: Run frontend tests
        working-directory: ./frontend
        run: npm test || echo "No tests found, skipping..."

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build
        
  backend:
    name: Backend (Node.js) Tests
    runs-on: ubuntu-latest
    needs: frontend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run backend tests
        working-directory: ./backend
        run: npm test || echo "No tests found, skipping..."
